# Generated by Django 4.0.4 on 2022-05-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='peliculas',
        ),
    ]
