# Generated by Django 4.0.4 on 2022-05-16 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_director_peliculas'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='peliculas',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Pelicula'),
            preserve_default=False,
        ),
    ]
