# Generated by Django 4.0.4 on 2022-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_director_peliculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='director',
            name='peliculas',
            field=models.ManyToManyField(to='catalog.pelicula'),
        ),
    ]
