# Generated by Django 4.0.4 on 2022-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_director_peliculas_director_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='peliculas',
            field=models.ManyToManyField(related_name='directores', to='catalog.pelicula'),
        ),
    ]
