# Generated by Django 4.0.4 on 2022-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_director_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='peliculas',
            field=models.ManyToManyField(to='catalog.pelicula'),
        ),
    ]
